<?php include('server.php') ?>
<!DOCTYPE html>
<html>
<head>
        <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
       <title>TextBids - Add item</title>
    
</head>
       <link rel="stylesheet" type="text/css" href="css/registration.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>        
        

<body>
    
    <div class="container-fluid bg">
        <div class = "col-md4 col-sm-2 col-xs-12"> </div>
        <div class = "col-md4 col-sm-4 col-xs-12">
	
        <form method="post" action="register.php" class="form-container">
       
		<?php include('errors.php'); ?>
            
                <div class="header">
                    <h2>Add new textbook sale</h3>
                </div>

                <!-- Textbook Title -->
                        <div class="form-group">
                            <label for="\Title">Title</label>
                            <input type="text" class="form-control" name="Title" placeholder="Textbook Title" required >
                        </div>

                <!-- ISBN -->
                        <div class="form-group">
                            <label for="\ISBN">ISBN</label>
                            <input type="text" class="form-control" name="ISBN" placeholder="(Optional)">
                        </div>
                
                <!-- Author -->
                        <div class="form-group">
                            <label for="\Author">Author</label>
                            <input type="text" class="form-control" name="Author" placeholder="Enter Author Credentials" required>
                        </div>
                
                <!-- Module -->
                        <div class="form-group">
                            <label for="\Module">Module</label>
                            <input type="text" class="form-control" name="Module" placeholder="Enter Module Name" required>
                        </div>
               
                <!-- Module Code -->
                        <div class="form-group">
                            <label for="\Module_Code">Module Code</label>
                            <select class="form-control " name="Module_Code" placeholder = "Select Module Code">
                                <option>AADS 511
                                </option><option>AASM 511
                                </option><option>ACCC 111
                                </option><option>ACCC 271
                                </option><option>ACCC 371
                                </option><option>ACCD 411
                                </option><option>ACCD 511
                                </option><option>ACCD 512
                                </option><option>ACCE 111
                                </option><option>ACCE 112
                                </option><option>ACCE 211
                                </option><option>ACCE 212
                                </option><option>ACCE 311
                                </option><option>ACCF 111
                                </option><option>ACCF 211
                                </option><option>ACCF 311
                                </option><option>ACCF 371
                                </option><option>ACCG 211
                                </option><option>ACCL 111
                                </option><option>ACCS 111
                                </option><option>ACFL 511
                                </option><option>ACFS 111
                                </option><option>ACFS 112
                                </option><option>ACMP 311
                                </option><option>ACPR 111
                                </option><option>ACWS 211
                                </option><option>ADSD 211
                                </option><option>AECM 111
                                </option><option>AECM 213
                                </option><option>AECM 311
                                </option><option>AECM 312
                                </option><option>AECM 313
                                </option><option>AECM 314
                                </option><option>AECM 411
                                </option><option>AECM 412
                                </option><option>AECM 413
                                </option><option>AECM 414
                                </option><option>AECM 415
                                </option><option>AECO 511
                                </option><option>AECP 211
                                </option><option>AEDM 111
                                </option><option>AEDM 314
                                </option><option>AEMS 511
                                </option><option>AEMT 511
                                </option><option>AENT 511
                                </option><option>AEXM 211
                                </option><option>AEXM 212
                                </option><option>AFAF 211
                                </option><option>AFAF 311
                                </option><option>AFAF 411
                                </option><option>AFAL 511
                                </option><option>AFKF 412
                                </option><option>AFKF 413
                                </option><option>AFLG 671
                                </option><option>AFLG 675
                                </option><option>AFLL 111
                                </option><option>AFLL 211
                                </option><option>AFLL 311
                                </option><option>AFLL 671
                                </option><option>AFLL 672
                                </option><option>AFLL 673
                                </option><option>AFLL 675
                                </option><option>AFLW 672
                                </option><option>AFNP 118
                                </option><option>AFRD 212
                                </option><option>AFRD 416
                                </option><option>AFRD 417
                                </option><option>AFRD 511
                                </option><option>AFRD 512
                                </option><option>AFRE 111
                                </option><option>AFRE 112
                                </option><option>AFRE 211
                                </option><option>AFRE 212
                                </option><option>AFRE 311
                                </option><option>AFRF 111
                                </option><option>AFRF 211
                                </option><option>AFRF 311
                                </option><option>AFRF 411
                                </option><option>AFRI 111
                                </option><option>AFRN 315
                                </option><option>AGCS 511
                                </option><option>AGLA 111
                                </option><option>AGLE 111
                                </option><option>AGLE 112
                                </option><option>AGSK 512
                                </option><option>AHIS 511
                                </option><option>AHPM 212
                                </option><option>AHPM 213
                                </option><option>AHPM 214
                                </option><option>AHPM 215
                                </option><option>AHPM 311
                                </option><option>AHPM 312
                                </option><option>AHPM 313
                                </option><option>AHPM 315
                                </option><option>AHPM 316
                                </option><option>AHPM 411
                                </option><option>AHPM 412
                                </option><option>AHPM 413
                                </option><option>AHSP 511
                                </option><option>AHSS 511
                                </option><option>AHVM 111
                                </option><option>AHVM 112
                                </option><option>AHVM 211
                                </option><option>AHVM 212
                                </option><option>AHVM 213
                                </option><option>AHVM 314
                                </option><option>AHVM 316
                                </option><option>AHVM 317
                                </option><option>AIFP 511
                                </option><option>AIIP 511
                                </option><option>AISP 511
                                </option><option>AKGS 111
                                </option><option>AKLR 112
                                </option><option>AKLR 113
                                </option><option>AKLR 211
                                </option><option>AKPN 315
                                </option><option>AKPN 316
                                </option><option>ALCG 511
                                </option><option>ALDA 111
                                </option><option>ALDE 111
                                </option><option>ALFA 511
                                </option><option>ALFE 511
                                </option><option>ALFS 511
                                </option><option>ALIF 511
                                </option><option>ALPE 511
                                </option><option>ALPI 511
                                </option><option>ALRE 511
                                </option><option>ALSE 511
                                </option><option>ALSI 511
                                </option><option>AMAT 511
                                </option><option>AMSS 511
                                </option><option>ANAV 111
                                </option><option>ANDM 211
                                </option><option>ANDM 212
                                </option><option>ANDM 213
                                </option><option>ANDM 312
                                </option><option>ANDM 313
                                </option><option>ANDM 314
                                </option><option>ANIM 511
                                </option><option>ANSM 211
                                </option><option>ANSM 214
                                </option><option>ANSM 311
                                </option><option>ANSM 312
                                </option><option>ANSM 313
                                </option><option>ANSM 314
                                </option><option>ANSM 411
                                </option><option>ANSM 412
                                </option><option>ANSM 414
                                </option><option>ANTS 111
                                </option><option>ANTS 671
                                </option><option>ANTS 672
                                </option><option>APLS 674
                                </option><option>APMM 117
                                </option><option>APMM 217
                                </option><option>APMM 317
                                </option><option>APMM 318
                                </option><option>APPM 111
                                </option><option>APPM 171
                                </option><option>APRO 511
                                </option><option>ARAB 111
                                </option><option>ARES 511
                                </option><option>ARTD 411
                                </option><option>ARTD 511
                                </option><option>ARTD 512
                                </option><option>ARTE 111
                                </option><option>ARTE 112
                                </option><option>ARTE 211
                                </option><option>ARTE 311
                                </option><option>ARTS 511
                                </option><option>ASAC 511
                                </option><option>ASTR 511
                                </option><option>ATEK 511
                                </option><option>ATPI 511
                                </option><option>ATSN 111
                                </option><option>ATSN 211
                                </option><option>ATSN 311
                                </option><option>AUDF 211
                                </option><option>AUDF 311
                                </option><option>AUDF 371
                                </option><option>AUDT 211
                                </option><option>AUDT 271
                                </option><option>AUDT 311
                                </option><option>AUDT 371
                                </option><option>AXDM 211
                                </option><option>AXDM 311
                                </option><option>BCDT 311
                                </option><option>BCHF 215
                                </option><option>BCHN 213
                                </option><option>BCHS 211
                                </option><option>BCHS 212
                                </option><option>BCHS 314
                                </option><option>BCHS 315
                                </option><option>BCHS 316
                                </option><option>BCHS 317
                                </option><option>BGYM 113
                                </option><option>BGYM 213
                                </option><option>BGYM 214
                                </option><option>BGYM 215
                                </option><option>BGYM 216
                                </option><option>BGYM 313
                                </option><option>BGYM 314
                                </option><option>BGYM 315
                                </option><option>BGYM 316
                                </option><option>BHIG 211
                                </option><option>BIBB 111
                                </option><option>BIOT 411
                                </option><option>BIYM 111
                                </option><option>BIYM 112
                                </option><option>BLCG 511
                                </option><option>BMAN 111
                                </option><option>BMAN 211
                                </option><option>BMAN 212
                                </option><option>BMAN 218
                                </option><option>BMAN 219
                                </option><option>BMAN 311
                                </option><option>BMAN 312
                                </option><option>BMAN 313
                                </option><option>BMAN 319
                                </option><option>BMAR 211
                                </option><option>BMAR 212
                                </option><option>BMAR 311
                                </option><option>BMAR 312
                                </option><option>BMAR 313
                                </option><option>BOPK 511
                                </option><option>BSKT 111
                                </option><option>BSTD 411
                                </option><option>BSTD 511
                                </option><option>BSTD 512
                                </option><option>BSTE 111
                                </option><option>BSTE 112
                                </option><option>BSTE 211
                                </option><option>BSTE 212
                                </option><option>BSTE 311
                                </option><option>BSTG 111
                                </option><option>BSWG 111
                                </option><option>BSWG 112
                                </option><option>BSWG 114
                                </option><option>BSWG 212
                                </option><option>BSWG 214
                                </option><option>BSWG 311
                                </option><option>BSWG 411
                                </option><option>BSWG 413
                                </option><option>BSWG 414
                                </option><option>BSWG 415
                                </option><option>BSWG 416
                                </option><option>BSWG 417
                                </option><option>BSWG 418
                                </option><option>BSWG 472
                                </option><option>BSWI 111
                                </option><option>BSWI 211
                                </option><option>BSWI 212
                                </option><option>BSWI 311
                                </option><option>BSWI 312
                                </option><option>BSWI 313
                                </option><option>BSWM 412
                                </option><option>BWIA 111
                                </option><option>BWIA 271
                                </option><option>BWIA 313
                                </option><option>BWIA 314
                                </option><option>BWIA 371
                                </option><option>BWOS 611
                                </option><option>BWOS 612
                                </option><option>BYBL 111
                                </option><option>BYBL 212
                                </option><option>BYBL 312
                                </option><option>BYBV 113
                                </option><option>BYBV 211
                                </option><option>BYBV 312
                                </option><option>CATD 411
                                </option><option>CATD 511
                                </option><option>CATD 512
                                </option><option>CATE 111
                                </option><option>CATE 112
                                </option><option>CATE 211
                                </option><option>CATE 311
                                </option><option>CCMM 511
                                </option><option>CCMM 514
                                </option><option>CCMM 515
                                </option><option>CCMM 516
                                </option><option>CCMM 517
                                </option><option>CDEK 511
                                </option><option>CEMI 211
                                </option><option>CEMI 213
                                </option><option>CEMI 311
                                </option><option>CEMI 313
                                </option><option>CEMI 315
                                </option><option>CEMI 316
                                </option><option>CEMI 411
                                </option><option>CEMI 415
                                </option><option>CEMI 417
                                </option><option>CEMI 418
                                </option><option>CEMI 419
                                </option><option>CEPS 612
                                </option><option>CFFM 111
                                </option><option>CFMA 111
                                </option><option>CHEM 111
                                </option><option>CHEM 311
                                </option><option>CHEN 211
                                </option><option>CHEN 212
                                </option><option>CHEN 213
                                </option><option>CHEN 312
                                </option><option>CHNM 111
                                </option><option>CISM 112
                                </option><option>CISM 211
                                </option><option>CISM 212
                                </option><option>CISM 213
                                </option><option>CISM 214
                                </option><option>CISM 311
                                </option><option>CISM 313
                                </option><option>CISM 314
                                </option><option>CLFE 115
                                </option><option>CLIN 611
                                </option><option>CLLE 211
                                </option><option>CMPF 111
                                </option><option>CMPF 111
                                </option><option>CMPG 111
                                </option><option>CMPG 112
                                </option><option>CMPG 115
                                </option><option>CMPG 171
                                </option><option>COMF 411
                                </option><option>COMF 511
                                </option><option>COMS 113
                                </option><option>COMS 114
                                </option><option>CSDM 111
                                </option><option>CSDM 211
                                </option><option>CSDM 212
                                </option><option>CSDM 213
                                </option><option>CSDM 214
                                </option><option>CSDM 215
                                </option><option>CSDM 311
                                </option><option>CSDM 312
                                </option><option>CSDM 315
                                </option><option>CSIE 611
                                </option><option>CSIE 612
                                </option><option>CSPM 211
                                </option><option>CSPM 212
                                </option><option>CSPM 213
                                </option><option>CSPM 311
                                </option><option>CSPM 312
                                </option><option>CSPM 313
                                </option><option>CSPM 411
                                </option><option>CSPM 412
                                </option><option>CSPM 413
                                </option><option>CSPM 414
                                </option><option>CSPM 415
                                </option><option>CSPM 416
                                </option><option>CSPM 418
                                </option><option>CTED 211
                                </option><option>CTEE 211
                                </option><option>CTEE 311
                                </option><option>CTEE 411
                                </option><option>CTSS 111
                                </option><option>CUDE 611
                                </option><option>CULV 211
                                </option><option>DEVS 111
                                </option><option>DMTM 317
                                </option><option>DOGM 211
                                </option><option>DOGM 311
                                </option><option>DOGM 312
                                </option><option>DOGM 611
                                </option><option>DOGM 672
                                </option><option>DRKN 211
                                </option><option>DRKS 111
                                </option><option>DRKS 311
                                </option><option>ECAM 311
                                </option><option>ECOD 411
                                </option><option>ECOD 511
                                </option><option>ECOD 512
                                </option><option>ECOE 111
                                </option><option>ECOE 112
                                </option><option>ECOE 211
                                </option><option>ECOE 212
                                </option><option>ECOE 311
                                </option><option>ECOM 515
                                </option><option>ECOM 516
                                </option><option>ECOM 517
                                </option><option>ECOM 518
                                </option><option>ECOM 519
                                </option><option>ECON 111
                                </option><option>ECON 112
                                </option><option>ECON 211
                                </option><option>ECON 212
                                </option><option>ECON 311
                                </option><option>ECON 312
                                </option><option>ECON 611
                                </option><option>ECON 614
                                </option><option>ECON 615
                                </option><option>EDCC 112
                                </option><option>EDCC 113
                                </option><option>EDCC 114
                                </option><option>EDCC 115
                                </option><option>EDCC 116
                                </option><option>EDCC 211
                                </option><option>EDCC 212
                                </option><option>EDCC 213
                                </option><option>EDCC 214
                                </option><option>EDCC 215
                                </option><option>EDCC 216
                                </option><option>EDCC 312
                                </option><option>EDCC 313
                                </option><option>EDCC 315
                                </option><option>EDCC 411
                                </option><option>EDCC 412
                                </option><option>EDCC 413
                                </option><option>EDCC 414
                                </option><option>EDCC 511
                                </option><option>EDCC 512
                                </option><option>EDCC 513
                                </option><option>EDCC 514
                                </option><option>EDCC 515
                                </option><option>EDCC 516
                                </option><option>EDCC 216
                                </option><option>EDCC 511
                                </option><option>EDDM 511
                                </option><option>EDDM 513
                                </option><option>EDDM 514
                                </option><option>EDDM 571
                                </option><option>EDEM 611
                                </option><option>EDEM 612
                                </option><option>EDIM 511
                                </option><option>EDIM 512
                                </option><option>EDIM 513
                                </option><option>EDIM 579
                                </option><option>EDMN 315
                                </option><option>EDTC 111
                                </option><option>EDTC 111
                                </option><option>EDTM 312
                                </option><option>EDTM 616
                                </option><option>EEII 413
                                </option><option>EERI 212
                                </option><option>EERI 213
                                </option><option>EERI 311
                                </option><option>EERI 313
                                </option><option>EERI 315
                                </option><option>EERI 412
                                </option><option>EERI 414
                                </option><option>EERI 418
                                </option><option>EESD 611
                                </option><option>EGDD 211
                                </option><option>EGDD 411
                                </option><option>EGDD 511
                                </option><option>EGDD 512
                                </option><option>EGDE 111
                                </option><option>EGDE 112
                                </option><option>EGDE 113
                                </option><option>EGDE 211
                                </option><option>EGDE 311
                                </option><option>EGPN 315
                                </option><option>EGYP 111
                                </option><option>EHIP 111
                                </option><option>EKIP 211
                                </option><option>EKIP 311
                                </option><option>EKRP 211
                                </option><option>EKRP 311
                                </option><option>ELEA 611
                                </option><option>ELYM 115
                                </option><option>ELYM 215
                                </option><option>ELYM 315
                                </option><option>ELYM 316
                                </option><option>EMLO 611
                                </option><option>ENAC 211
                                </option><option>ENAF 211
                                </option><option>ENAF 311
                                </option><option>ENAF 411
                                </option><option>ENFF 111
                                </option><option>ENFF 211
                                </option><option>ENFF 311
                                </option><option>ENFF 411
                                </option><option>ENFI 111
                                </option><option>ENGD 212
                                </option><option>ENGD 416
                                </option><option>ENGD 417
                                </option><option>ENGD 511
                                </option><option>ENGD 512
                                </option><option>ENGE 111
                                </option><option>ENGE 212
                                </option><option>ENGE 311
                                </option><option>ENGF 211
                                </option><option>ENGL 113
                                </option><option>ENGV 111
                                </option><option>ENGV 211
                                </option><option>ENLG 672
                                </option><option>ENLG 674
                                </option><option>ENLG 675
                                </option><option>ENLG 679
                                </option><option>ENLG 682
                                </option><option>ENLL 111
                                </option><option>ENLL 211
                                </option><option>ENLL 311
                                </option><option>ENLL 676
                                </option><option>ENLL 677
                                </option><option>ENLL 678
                                </option><option>ENLL 679
                                </option><option>ENLL 688
                                </option><option>ENLL 690
                                </option><option>ENLS 111
                                </option><option>ENTN 315
                                </option><option>EPPM 111
                                </option><option>EPSY 611
                                </option><option>EPSY 612
                                </option><option>EPSY 614
                                </option><option>ERTP 671
                                </option><option>ESPN 315
                                </option><option>ETED 211
                                </option><option>ETEE 212
                                </option><option>ETEE 311
                                </option><option>ETEE 411
                                </option><option>ETIE 211
                                </option><option>ETIE 212
                                </option><option>ETIE 311
                                </option><option>ETIE 313
                                </option><option>ETIE 314
                                </option><option>ETIE 672
                                </option><option>ETIE 875
                                </option><option>ETTM 511
                                </option><option>EUCE 511
                                </option><option>EXTM 514
                                </option><option>EXTM 515
                                </option><option>EXTM 516
                                </option><option>FBCG 211
                                </option><option>FCHG 312
                                </option><option>FCHG 412
                                </option><option>FETC 111
                                </option><option>FETM 111
                                </option><option>FETP 111
                                </option><option>FIAP 173
                                </option><option>FILH 674
                                </option><option>FILH 679
                                </option><option>FINM 271
                                </option><option>FKLG 211
                                </option><option>FKLG 212
                                </option><option>FKLG 312
                                </option><option>FKLG 412
                                </option><option>FLGX 113
                                </option><option>FLGX 114
                                </option><option>FLGX 213
                                </option><option>FLGX 312
                                </option><option>FLGX 313
                                </option><option>FLGX 314
                                </option><option>FLPV 213
                                </option><option>FLPX 113
                                </option><option>FMAN 271
                                </option><option>FMSG 212
                                </option><option>FMSG 312
                                </option><option>FMSG 412
                                </option><option>FNSM 111
                                </option><option>FOER 611
                                </option><option>FORP 112
                                </option><option>FORP 214
                                </option><option>FORP 215
                                </option><option>FORP 313
                                </option><option>FORP 674
                                </option><option>FORP 675
                                </option><option>FORP 676
                                </option><option>FPFG 211
                                </option><option>FPFG 312
                                </option><option>FPFG 412
                                </option><option>FPKG 112
                                </option><option>FPKG 113
                                </option><option>FPKG 211
                                </option><option>FPKG 313
                                </option><option>FPKG 414
                                </option><option>FPUN 315
                                </option><option>FREB 111
                                </option><option>FREN 111
                                </option><option>FREN 211
                                </option><option>FREN 311
                                </option><option>FROF 571
                                </option><option>FROG 571
                                </option><option>FROL 571
                                </option><option>FROP 571
                                </option><option>FROS 571
                                </option><option>FSET 511
                                </option><option>FSKS 111
                                </option><option>FSKS 113
                                </option><option>FSKS 211
                                </option><option>FSKS 212
                                </option><option>FSKS 311
                                </option><option>FSKS 312
                                </option><option>GBGK 511
                                </option><option>GDKN 211
                                </option><option>GENL 311
                                </option><option>GEOD 411
                                </option><option>GEOD 511
                                </option><option>GEOD 512
                                </option><option>GEOE 111
                                </option><option>GEOE 112
                                </option><option>GEOE 211
                                </option><option>GEOE 212
                                </option><option>GEOE 311
                                </option><option>GEOG 111
                                </option><option>GEOG 171
                                </option><option>GEOM 113
                                </option><option>GEOM 214
                                </option><option>GEOM 215
                                </option><option>GEOM 316
                                </option><option>GEOM 317
                                </option><option>GEOS 211
                                </option><option>GERB 111
                                </option><option>GERM 111
                                </option><option>GERM 211
                                </option><option>GERM 311
                                </option><option>GFPN 315
                                </option><option>GGFS 111
                                </option><option>GGFS 112
                                </option><option>GGFS 211
                                </option><option>GGFS 212
                                </option><option>GGFS 311
                                </option><option>GGFS 312
                                </option><option>GHRM 571
                                </option><option>GLGN 112
                                </option><option>GLGN 211
                                </option><option>GLGN 311
                                </option><option>GNSM 111
                                </option><option>GNSM 211
                                </option><option>GNSM 311
                                </option><option>GRFI 112
                                </option><option>GRFI 211
                                </option><option>GRFM 311
                                </option><option>GRFM 411
                                </option><option>GRFO 112
                                </option><option>GRFO 212
                                </option><option>GRFO 213
                                </option><option>GRFO 313
                                </option><option>GRFO 414
                                </option><option>GRKS 112
                                </option><option>GRKS 113
                                </option><option>GRKS 172
                                </option><option>GRKS 211
                                </option><option>GRKS 312
                                </option><option>GRKS 611
                                </option><option>GRKS 671
                                </option><option>GRKS 672
                                </option><option>GRKS 673
                                </option><option>GRKS 674
                                </option><option>GRKS 675
                                </option><option>GSAN 315
                                </option><option>GSGK 511
                                </option><option>HBRM 211
                                </option><option>HCOM 117
                                </option><option>HDEV 111
                                </option><option>HDEV 211
                                </option><option>HDEV 311
                                </option><option>HIKS 111
                                </option><option>HIRL 115
                                </option><option>HIRL 211
                                </option><option>HIRL 215
                                </option><option>HIRL 311
                                </option><option>HISD 411
                                </option><option>HISD 511
                                </option><option>HISD 512
                                </option><option>HISE 111
                                </option><option>HISE 112
                                </option><option>HISE 211
                                </option><option>HISE 212
                                </option><option>HISE 311
                                </option><option>HISE 611
                                </option><option>HISS 211
                                </option><option>HIST 112
                                </option><option>HIST 212
                                </option><option>HIST 213
                                </option><option>HIST 312
                                </option><option>HLND 111
                                </option><option>HMDC 111
                                </option><option>HMDC 112
                                </option><option>HMPA 111
                                </option><option>HMPR 111
                                </option><option>HMPS 111
                                </option><option>HMSA 111
                                </option><option>HMSC 111
                                </option><option>HMSC 112
                                </option><option>HMSC 113
                                </option><option>HMSC 114
                                </option><option>HOML 211
                                </option><option>HOML 611
                                </option><option>HOMV 671
                                </option><option>HPEC 111
                                </option><option>HPEC 112
                                </option><option>HPEC 211
                                </option><option>HPEC 214
                                </option><option>HPOP 111
                                </option><option>HPOP 211
                                </option><option>HPOP 212
                                </option><option>HPOP 311
                                </option><option>HPOP 313
                                </option><option>HPPA 511
                                </option><option>HPPA 512
                                </option><option>HPPA 513
                                </option><option>HPPA 514
                                </option><option>HRMA 111
                                </option><option>HRMA 211
                                </option><option>HRMA 311
                                </option><option>HSCN 319
                                </option><option>HTOD 115
                                </option><option>HTOD 215
                                </option><option>HTOD 216
                                </option><option>HTOD 217
                                </option><option>HTOD 315
                                </option><option>HTOD 316
                                </option><option>ICOM 111
                                </option><option>IELS 671
                                </option><option>IKSM 111
                                </option><option>IKSM 112
                                </option><option>IKSM 113
                                </option><option>IKSM 114
                                </option><option>IKSM 115
                                </option><option>IKSM 211
                                </option><option>IKSM 212
                                </option><option>IKSM 213
                                </option><option>IKSM 214
                                </option><option>IKSM 215
                                </option><option>IKSM 311
                                </option><option>IKSM 312
                                </option><option>IKSM 313
                                </option><option>INFS 111
                                </option><option>INFS 113
                                </option><option>INGB 311
                                </option><option>INGB 314
                                </option><option>INGB 315
                                </option><option>INGB 316
                                </option><option>INGB 413
                                </option><option>INGB 417
                                </option><option>INGM 111
                                </option><option>INGM 211
                                </option><option>INGM 212
                                </option><option>INGM 311
                                </option><option>INGM 312
                                </option><option>INGM 313
                                </option><option>INGM 412
                                </option><option>INGM 413
                                </option><option>INGM 415
                                </option><option>INGM 416
                                </option><option>INGM 417
                                </option><option>INSC 511
                                </option><option>INTD 411
                                </option><option>INTD 511
                                </option><option>INTE 111
                                </option><option>INTE 112
                                </option><option>INTE 211
                                </option><option>INTE 311
                                </option><option>INYM 111
                                </option><option>INYM 113
                                </option><option>INYM 216
                                </option><option>INYM 217
                                </option><option>INYM 218
                                </option><option>INYM 219
                                </option><option>INYM 313
                                </option><option>INYM 314
                                </option><option>INYM 316
                                </option><option>IOPS 111
                                </option><option>IOPS 211
                                </option><option>IOPS 212
                                </option><option>IOPS 311
                                </option><option>IPSM 111
                                </option><option>ISCS 611
                                </option><option>ISSP 511
                                </option><option>ITEE 211
                                </option><option>ITEE 311
                                </option><option>ITEE 412
                                </option><option>ITRW 112
                                </option><option>ITRW 115
                                </option><option>ITRW 211
                                </option><option>ITRW 212
                                </option><option>ITRW 213
                                </option><option>ITRW 214
                                </option><option>ITRW 311
                                </option><option>ITRW 313
                                </option><option>ITRW 315
                                </option><option>ITRW 316
                                </option><option>ITRW 317
                                </option><option>ITSP 111
                                </option><option>ITSP 113
                                </option><option>ITSP 114
                                </option><option>IURE 411
                                </option><option>IURE 413
                                </option><option>IURE 414
                                </option><option>IURI 111
                                </option><option>IURI 171
                                </option><option>IURI 172
                                </option><option>IURI 173
                                </option><option>IURI 174
                                </option><option>IURI 211
                                </option><option>IURI 212
                                </option><option>IURI 213
                                </option><option>IURI 271
                                </option><option>IURI 272
                                </option><option>IURI 273
                                </option><option>IURI 274
                                </option><option>IURI 311
                                </option><option>IURI 312
                                </option><option>IURI 371
                                </option><option>IURI 372
                                </option><option>IURI 373
                                </option><option>IURI 374
                                </option><option>IURI 375
                                </option><option>IURI 411
                                </option><option>IURI 412
                                </option><option>IURI 413
                                </option><option>IURI 414
                                </option><option>IURM 411
                                </option><option>IURM 413
                                </option><option>IURP 411
                                </option><option>IURP 412
                                </option><option>IURP 413
                                </option><option>KATE 211
                                </option><option>KATE 212
                                </option><option>KCMJ 673
                                </option><option>KCMN 671
                                </option><option>KCMO 672
                                </option><option>KCOM 111
                                </option><option>KCOM 112
                                </option><option>KCOM 114
                                </option><option>KCOM 211
                                </option><option>KCOM 213
                                </option><option>KCOM 214
                                </option><option>KCOM 218
                                </option><option>KCOM 311
                                </option><option>KCOM 314
                                </option><option>KCOM 315
                                </option><option>KCOM 316
                                </option><option>KCOM 317
                                </option><option>KCOM 318
                                </option><option>KCOM 371
                                </option><option>KCOM 372
                                </option><option>KDGE 211
                                </option><option>KDGE 312
                                </option><option>KDGE 611
                                </option><option>KDGE 672
                                </option><option>KERG 611
                                </option><option>KSGS 113
                                </option><option>KSGS 212
                                </option><option>KSGS 312
                                </option><option>LAAD 211
                                </option><option>LAAD 411
                                </option><option>LAAD 511
                                </option><option>LAAE 111
                                </option><option>LAAE 211
                                </option><option>LABD 211
                                </option><option>LABD 411
                                </option><option>LAND 211
                                </option><option>LAND 411
                                </option><option>LANE 211
                                </option><option>LANE 311
                                </option><option>LARM 111
                                </option><option>LARM 211
                                </option><option>LARM 311
                                </option><option>LASD 211
                                </option><option>LASD 411
                                </option><option>LATN 112
                                </option><option>LATN 211
                                </option><option>LATN 677
                                </option><option>LATN 681
                                </option><option>LATN 682
                                </option><option>LATN 683
                                </option><option>LATN 684
                                </option><option>LATN 685
                                </option><option>LATN 686
                                </option><option>LDIS 315
                                </option><option>LEON 611
                                </option><option>LEON 612
                                </option><option>LEON 613
                                </option><option>LEON 614
                                </option><option>LEON 971
                                </option><option>LESE 112
                                </option><option>LESE 212
                                </option><option>LEWV 112
                                </option><option>LEWV 211
                                </option><option>LGAM 115
                                </option><option>LGAM 216
                                </option><option>LGAM 317
                                </option><option>LGAM 318
                                </option><option>LIFD 411
                                </option><option>LIFD 511
                                </option><option>LIFD 512
                                </option><option>LIFE 111
                                </option><option>LIFE 112
                                </option><option>LIFE 211
                                </option><option>LIFE 212
                                </option><option>LIFE 311
                                </option><option>LITA 312
                                </option><option>LITA 313
                                </option><option>LITG 211
                                </option><option>LITG 413
                                </option><option>LITH 113
                                </option><option>LITH 312
                                </option><option>LITH 313
                                </option><option>LITH 314
                                </option><option>LITK 611
                                </option><option>LITK 671
                                </option><option>LLOD 211
                                </option><option>LLOD 411
                                </option><option>LLOD 511
                                </option><option>LLOD 512
                                </option><option>LMNM 211
                                </option><option>LMNM 311
                                </option><option>LMNM 312
                                </option><option>LOBO 571
                                </option><option>LOCK 571
                                </option><option>LOCN 319
                                </option><option>LOHA 571
                                </option><option>LOHO 611
                                </option><option>LOHO 671
                                </option><option>LOPV 111
                                </option><option>LORD 411
                                </option><option>LORE 111
                                </option><option>LORE 211
                                </option><option>LORE 311
                                </option><option>LOSE 211
                                </option><option>LPRA 111
                                </option><option>LPRA 211
                                </option><option>LPRA 311
                                </option><option>LPRA 312
                                </option><option>LSED 518
                                </option><option>LSFP 112
                                </option><option>LSFP 212
                                </option><option>LSFP 312
                                </option><option>LSIE 518
                                </option><option>LSIP 111
                                </option><option>LSKA 211
                                </option><option>LSKA 311
                                </option><option>LSKM 211
                                </option><option>LSKN 312
                                </option><option>LSKP 311
                                </option><option>LSKS 111
                                </option><option>LSPP 411
                                </option><option>LTCA 671
                                </option><option>LTLL 611
                                </option><option>MACC 211
                                </option><option>MACC 271
                                </option><option>MACC 311
                                </option><option>MALA 211
                                </option><option>MALA 311
                                </option><option>MATD 211
                                </option><option>MATD 312
                                </option><option>MATD 411
                                </option><option>MATD 413
                                </option><option>MATD 511
                                </option><option>MATD 512
                                </option><option>MATD 611
                                </option><option>MATE 111
                                </option><option>MATE 211
                                </option><option>MATE 311
                                </option><option>MATE 671
                                </option><option>MATF 111
                                </option><option>MATF 311
                                </option><option>MATH 111
                                </option><option>MATH 211
                                </option><option>MATL 112
                                </option><option>MATL 212
                                </option><option>MATL 311
                                </option><option>MATV 111
                                </option><option>MAYM 115
                                </option><option>MAYM 116
                                </option><option>MAYM 117
                                </option><option>MAYM 217
                                </option><option>MAYM 317
                                </option><option>MAYM 318
                                </option><option>MBWA 112
                                </option><option>MBWK 112
                                </option><option>MBWK 114
                                </option><option>MBWK 216
                                </option><option>MBWK 217
                                </option><option>MBWK 218
                                </option><option>MBWK 219
                                </option><option>MBWK 315
                                </option><option>MBWK 316
                                </option><option>MBXA 211
                                </option><option>MBXG 114
                                </option><option>MBXN 211
                                </option><option>MBXR 112
                                </option><option>MBXR 114
                                </option><option>MBXR 214
                                </option><option>MBXR 216
                                </option><option>MBXR 217
                                </option><option>MBXR 218
                                </option><option>MBXR 219
                                </option><option>MBXR 216
                                </option><option>MBXS 211
                                </option><option>MBXT 211
                                </option><option>MCBN 111
                                </option><option>MCBN 171
                                </option><option>MCHE 114
                                </option><option>MCHE 115
                                </option><option>MCHE 215
                                </option><option>MCHE 216
                                </option><option>MCHE 315
                                </option><option>MCHE 316
                                </option><option>MCLM 113
                                </option><option>MDAC 271
                                </option><option>MFPC 111
                                </option><option>MFPC 411
                                </option><option>MFPD 211
                                </option><option>MFPD 411
                                </option><option>MFPF 111
                                </option><option>MFPF 311
                                </option><option>MISS 211
                                </option><option>MISS 213
                                </option><option>MISS 311
                                </option><option>MISS 312
                                </option><option>MISS 672
                                </option><option>MIYM 311
                                </option><option>MIYM 411
                                </option><option>MKBN 211
                                </option><option>MKBS 211
                                </option><option>MKBS 212
                                </option><option>MKBS 313
                                </option><option>MKBS 314
                                </option><option>MKBS 316
                                </option><option>MKBS 317
                                </option><option>MKBX 213
                                </option><option>MKPN 111
                                </option><option>MLAW 111
                                </option><option>MLAW 211
                                </option><option>MLED 572
                                </option><option>MLED 574
                                </option><option>MLED 575
                                </option><option>MLED 576
                                </option><option>MLIT 111
                                </option><option>MOVD 411
                                </option><option>MOVE 111
                                </option><option>MOVE 211
                                </option><option>MOVE 311
                                </option><option>MPAD 877
                                </option><option>MSVD 511
                                </option><option>MSVD 512
                                </option><option>MTEC 111
                                </option><option>MTED 211
                                </option><option>MTED 311
                                </option><option>MTHS 111
                                </option><option>MTHS 112
                                </option><option>MTHS 113
                                </option><option>MTHS 114
                                </option><option>MTHS 115
                                </option><option>MTHS 119
                                </option><option>MTHS 171
                                </option><option>MTHS 173
                                </option><option>MTLS 211
                                </option><option>MUMA 112
                                </option><option>MUMA 113
                                </option><option>MUMA 114
                                </option><option>MUMA 212
                                </option><option>MUMA 313
                                </option><option>MUME 113
                                </option><option>MUSB 312
                                </option><option>MUSB 317
                                </option><option>MUSC 217
                                </option><option>MUSD 111
                                </option><option>MUSD 119
                                </option><option>MUSE 211
                                </option><option>MUSE 311
                                </option><option>MUSE 411
                                </option><option>MUSH 171
                                </option><option>MUSH 271
                                </option><option>MUSH 371
                                </option><option>MUSI 111
                                </option><option>MUSJ 113
                                </option><option>MUSK 311
                                </option><option>MUSL 177
                                </option><option>MUSM 411
                                </option><option>MUSO 111
                                </option><option>MUSO 113
                                </option><option>MUSO 211
                                </option><option>MUSO 213
                                </option><option>MUSO 311
                                </option><option>MUSO 313
                                </option><option>MUSO 411
                                </option><option>MUSP 174
                                </option><option>MUSS 219
                                </option><option>MUST 111
                                </option><option>MUST 119
                                </option><option>MUST 211
                                </option><option>MUST 219
                                </option><option>MUST 311
                                </option><option>MUST 319
                                </option><option>MUSU 177
                                </option><option>MUSU 179
                                </option><option>MUSW 411
                                </option><option>MUSX 111
                                </option><option>MUSX 211
                                </option><option>MUSX 212
                                </option><option>MUSX 311
                                </option><option>MUSY 117
                                </option><option>MUSY 217
                                </option><option>MUSY 317
                                </option><option>MWKC 874
                                </option><option>MWKC 875
                                </option><option>MWKF 878
                                </option><option>MZME 119
                                </option><option>MZSD 119
                                </option><option>MZSL 177
                                </option><option>MZSN 119
                                </option><option>MZSO 119
                                </option><option>MZSO 219
                                </option><option>MZSO 319
                                </option><option>MZSP 179
                                </option><option>MZSS 219
                                </option><option>MZSS 319
                                </option><option>MZST 219
                                </option><option>MZST 319
                                </option><option>MZSU 177
                                </option><option>MZSU 179
                                </option><option>MZSU 279
                                </option><option>MZSU 379
                                </option><option>MZSY 219
                                </option><option>MZSY 319
                                </option><option>NADM 111
                                </option><option>NADM 112
                                </option><option>NADM 211
                                </option><option>NAVR 611
                                </option><option>NCHE 111
                                </option><option>NCHE 171
                                </option><option>NCHM 111
                                </option><option>NCHM 211
                                </option><option>NCHM 311
                                </option><option>NDNK 512
                                </option><option>NEDM 111
                                </option><option>NEDM 211
                                </option><option>NFPF 411
                                </option><option>NFSK 511
                                </option><option>NPHY 111
                                </option><option>NPHY 171
                                </option><option>NRMM 411
                                </option><option>NSCN 315
                                </option><option>NSCP 111
                                </option><option>NSCP 112
                                </option><option>NSCT 211
                                </option><option>NSDT 111
                                </option><option>NSET 111
                                </option><option>NSET 211
                                </option><option>NSET 311
                                </option><option>NSGT 111
                                </option><option>NSHT 211
                                </option><option>NSKT 211
                                </option><option>NSMT 211
                                </option><option>NSMT 311
                                </option><option>NSSP 111
                                </option><option>NSSP 112
                                </option><option>NSSP 211
                                </option><option>NSTL 111
                                </option><option>NTES 111
                                </option><option>NTES 112
                                </option><option>NTES 211
                                </option><option>NTES 311
                                </option><option>NTES 3v2
                                </option><option>NTES 3v3
                                </option><option>NTES 612
                                </option><option>NTES 673
                                </option><option>NUTB 111
                                </option><option>NUTB 112
                                </option><option>NUTB 211
                                </option><option>NUTC 471
                                </option><option>NUTC 882
                                </option><option>NUTE 874
                                </option><option>NUTF 471
                                </option><option>NUTG 671
                                </option><option>NUTP 671
                                </option><option>NUTP 874
                                </option><option>NUTS 671
                                </option><option>NUTS 876
                                </option><option>NUTT 311
                                </option><option>NUTT 471
                                </option><option>NWCN 319
                                </option><option>NWPK 511
                                </option><option>NWPK 512
                                </option><option>NWSK 513
                                </option><option>NWSK 514
                                </option><option>OBAD 112
                                </option><option>OMBO 613
                                </option><option>OMBO 614
                                </option><option>OMBO 678
                                </option><option>OMSB 611
                                </option><option>ONWB 611
                                </option><option>ONWR 611
                                </option><option>OPAN 315
                                </option><option>OPLN 111
                                </option><option>OPLN 112
                                </option><option>OPLN 211
                                </option><option>OPLN 212
                                </option><option>OPLN 311
                                </option><option>OPLN 312
                                </option><option>OPLN 313
                                </option><option>OPLN 314
                                </option><option>OPSK 612
                                </option><option>OPSK 613
                                </option><option>ORAK 511
                                </option><option>ORLK 511
                                </option><option>OTES 111
                                </option><option>OTES 112
                                </option><option>OTES 211
                                </option><option>OTES 311
                                </option><option>OTES 4v1
                                </option><option>OTES 4v2
                                </option><option>OTES 4v3
                                </option><option>OTES 612
                                </option><option>OTES 674
                                </option><option>PADM 111
                                </option><option>PADM 118
                                </option><option>PAST 211
                                </option><option>PAST 311
                                </option><option>PAST 671
                                </option><option>PAYM 117
                                </option><option>PAYM 118
                                </option><option>PAYM 211
                                </option><option>PAYM 212
                                </option><option>PAYM 215
                                </option><option>PAYM 311
                                </option><option>PCDG 572
                                </option><option>PCMP 571
                                </option><option>PCSR 571
                                </option><option>PCTL 572
                                </option><option>PEFF 111
                                </option><option>PEFF 211
                                </option><option>PEFF 311
                                </option><option>PEFF 411
                                </option><option>PEFI 111
                                </option><option>PEMM 512
                                </option><option>PESP 111
                                </option><option>PESP 211
                                </option><option>PESP 511
                                </option><option>PFLS 511
                                </option><option>PGDD 511
                                </option><option>PGDD 512
                                </option><option>PGDD 513
                                </option><option>PGDL 511
                                </option><option>PGDL 512
                                </option><option>PGDP 514
                                </option><option>PHIL 111
                                </option><option>PHIL 112
                                </option><option>PHIL 211
                                </option><option>PHIL 311
                                </option><option>PHIL 312
                                </option><option>PHMM 112
                                </option><option>PHSD 411
                                </option><option>PHSD 511
                                </option><option>PHSD 512
                                </option><option>PHSE 111
                                </option><option>PHSE 112
                                </option><option>PHSE 112
                                </option><option>PHSE 211
                                </option><option>PHSE 212
                                </option><option>PHSE 311
                                </option><option>PHSE 611
                                </option><option>PHSE 612
                                </option><option>PHYM 118
                                </option><option>PHYM 215
                                </option><option>PHYM 216
                                </option><option>PHYM 315
                                </option><option>PHYM 316
                                </option><option>PHYM 317
                                </option><option>PHYM 318
                                </option><option>PLKN 213
                                </option><option>PLKS 111
                                </option><option>PLKS 171
                                </option><option>PLKS 312
                                </option><option>PNSM 311
                                </option><option>PNSM 411
                                </option><option>POLI 112
                                </option><option>POLI 113
                                </option><option>POLI 213
                                </option><option>POLI 312
                                </option><option>POLI 313
                                </option><option>POLI 314
                                </option><option>POLT 112
                                </option><option>POMA 113
                                </option><option>POMA 114
                                </option><option>POMA 115
                                </option><option>POMA 212
                                </option><option>POMA 317
                                </option><option>PPEP 171
                                </option><option>PPSE 211
                                </option><option>PPSE 411
                                </option><option>PSDT 111
                                </option><option>PSYC 111
                                </option><option>PSYC 211
                                </option><option>PSYC 212
                                </option><option>PSYC 311
                                </option><option>PSYC 312
                                </option><option>PSYC 879
                                </option><option>PSYC 880
                                </option><option>PSYC 883
                                </option><option>PSYC 884
                                </option><option>PSYC 885
                                </option><option>PSYH 671
                                </option><option>PSYH 672
                                </option><option>PSYV 879
                                </option><option>PSYV 880
                                </option><option>PSYV 885
                                </option><option>PUMA 112
                                </option><option>PUMA 113
                                </option><option>PUMA 212
                                </option><option>PUMA 213
                                </option><option>PUMA 313
                                </option><option>PUMA 314
                                </option><option>PUMA 315
                                </option><option>PUMA 316
                                </option><option>RALT 211
                                </option><option>RCDP 211
                                </option><option>RECP 671
                                </option><option>RECP 672
                                </option><option>RECP 673
                                </option><option>RECP 674
                                </option><option>REDM 271
                                </option><option>REII 111
                                </option><option>REII 211
                                </option><option>REII 312
                                </option><option>REII 313
                                </option><option>REII 414
                                </option><option>REIP 671
                                </option><option>REKP 671
                                </option><option>REKP 674
                                </option><option>REKP 675
                                </option><option>RELT 211
                                </option><option>REMS 311
                                </option><option>RESF 411
                                </option><option>RESF 412
                                </option><option>RESF 511
                                </option><option>RFLS 111
                                </option><option>RHWP 111
                                </option><option>RIRS 311
                                </option><option>RKKX 114
                                </option><option>RKKX 115
                                </option><option>RKKX 214
                                </option><option>RKKX 215
                                </option><option>RKKX 216
                                </option><option>RKKX 314
                                </option><option>RKKX 315
                                </option><option>RLBK 271
                                </option><option>RLCA 271
                                </option><option>RLSD 171
                                </option><option>RLSP 371
                                </option><option>RLSS 211
                                </option><option>RMAT 111
                                </option><option>RMAT 171
                                </option><option>RMAT 211
                                </option><option>ROLT 211
                                </option><option>RPLT 211
                                </option><option>RRTL 271
                                </option><option>RSLT 211
                                </option><option>RSPR 671
                                </option><option>RSVD 511
                                </option><option>RSVD 512
                                </option><option>RTAL 171
                                </option><option>RTCL 111
                                </option><option>RWEL 111
                                </option><option>RWLT 211
                                </option><option>RXLT 211
                                </option><option>RZLT 211
                                </option><option>SANL 112
                                </option><option>SANL 213
                                </option><option>SANL 313
                                </option><option>SANL 314
                                </option><option>SASL 111
                                </option><option>SASL 211
                                </option><option>SASL 311
                                </option><option>SBES 111
                                </option><option>SBRS 211
                                </option><option>SBRS 311
                                </option><option>SBRS 411
                                </option><option>SBSL 412
                                </option><option>SBSS 111
                                </option><option>SBSS 211
                                </option><option>SBSS 311
                                </option><option>SBSS 412
                                </option><option>SBUS 111
                                </option><option>SEAF 211
                                </option><option>SEAF 311
                                </option><option>SEAF 411
                                </option><option>SECF 412
                                </option><option>SECF 413
                                </option><option>SEFF 111
                                </option><option>SEFF 211
                                </option><option>SEFF 311
                                </option><option>SEFF 411
                                </option><option>SEFI 111
                                </option><option>SEFV 111
                                </option><option>SEFV 211
                                </option><option>SEMD 211
                                </option><option>SEMD 411
                                </option><option>SEMD 511
                                </option><option>SEMD 512
                                </option><option>SEME 111
                                </option><option>SEME 211
                                </option><option>SEME 311
                                </option><option>SEMT 112
                                </option><option>SEMT 113
                                </option><option>SEMT 211
                                </option><option>SEMT 312
                                </option><option>SEMT 611
                                </option><option>SEMT 671
                                </option><option>SEMT 672
                                </option><option>SEMT 673
                                </option><option>SEMT 674
                                </option><option>SEMT 675
                                </option><option>SEMT 676
                                </option><option>SEMT 677
                                </option><option>SEMT 678
                                </option><option>SEND 511
                                </option><option>SEND 512
                                </option><option>SENE 111
                                </option><option>SETM 111
                                </option><option>SETM 211
                                </option><option>SETM 311
                                </option><option>SFBM 111
                                </option><option>SFBM 171
                                </option><option>SFCM 111
                                </option><option>SFCM 171
                                </option><option>SFEM 171
                                </option><option>SFEM 172
                                </option><option>SFMM 111
                                </option><option>SFMM 171
                                </option><option>SFPM 111
                                </option><option>SFPM 171
                                </option><option>SFSM 111
                                </option><option>SKRK 111
                                </option><option>SKRK 211
                                </option><option>SKRK 311
                                </option><option>SKRK 671
                                </option><option>SLOE 111
                                </option><option>SNSE 111
                                </option><option>SOCF 111
                                </option><option>SOCF 211
                                </option><option>SOCL 111
                                </option><option>SOCL 211
                                </option><option>SOCL 212
                                </option><option>SOCL 311
                                </option><option>SOCL 312
                                </option><option>SOCY 111
                                </option><option>SOFF 111
                                </option><option>SOFF 211
                                </option><option>SOFF 311
                                </option><option>SOFF 411
                                </option><option>SOFF 211
                                </option><option>SOFI 111
                                </option><option>SOFV 111
                                </option><option>SOFV 211
                                </option><option>SPKK 511
                                </option><option>SPSO 411
                                </option><option>SPSO 411
                                </option><option>SSCE 111
                                </option><option>SSCN 315
                                </option><option>SSCO 111
                                </option><option>SSLL 112
                                </option><option>SSLL 212
                                </option><option>SSLL 312
                                </option><option>SSSE 111
                                </option><option>SSSE 112
                                </option><option>SSTD 511
                                </option><option>STFM 111
                                </option><option>STFM 112
                                </option><option>STFM 211
                                </option><option>STFM 212
                                </option><option>STFM 311
                                </option><option>STFM 312
                                </option><option>STOM 211
                                </option><option>STOM 311
                                </option><option>STOM 312
                                </option><option>STTF 111
                                </option><option>STTF 115
                                </option><option>STTF 215
                                </option><option>STTK 214
                                </option><option>STTK 312
                                </option><option>STTN 111
                                </option><option>STTN 115
                                </option><option>STTN 215
                                </option><option>STTN 315
                                </option><option>TAXC 211
                                </option><option>TAXC 271
                                </option><option>TAXC 371
                                </option><option>TAXF 211
                                </option><option>TAXF 311
                                </option><option>TAXF 371
                                </option><option>TAXM 877
                                </option><option>TECD 211
                                </option><option>TECD 411
                                </option><option>TECE 211
                                </option><option>TECE 311
                                </option><option>TECE 611
                                </option><option>TECH 571
                                </option><option>TECK 315
                                </option><option>TECM 111
                                </option><option>TECM 211
                                </option><option>TECM 212
                                </option><option>TECM 311
                                </option><option>TECM 313
                                </option><option>TEOL 111
                                </option><option>TEOL 112
                                </option><option>TEWE 111
                                </option><option>TGNO 511
                                </option><option>TGWN 211
                                </option><option>TGWN 213
                                </option><option>TGWN 311
                                </option><option>TGWN 312
                                </option><option>TLAS 612
                                </option><option>TMBP 111
                                </option><option>TMBP 211
                                </option><option>TMBP 311
                                </option><option>TMBP 312
                                </option><option>TMBP 671
                                </option><option>TMBP 672
                                </option><option>TMBP 673
                                </option><option>TNAV 671
                                </option><option>TOAF 612
                                </option><option>TOAF 671
                                </option><option>TOAF 672
                                </option><option>TOAF 673
                                </option><option>TRVD 511
                                </option><option>TRVD 512
                                </option><option>TSCN 315
                                </option><option>TSMN 315
                                </option><option>TSNN 315
                                </option><option>TTED 111
                                </option><option>TTED 511
                                </option><option>TTED 512
                                </option><option>VGAK 511
                                </option><option>VGHB 311
                                </option><option>VGLO 611
                                </option><option>VGLO 612
                                </option><option>VHTB 311
                                </option><option>VKLE 114
                                </option><option>VKLE 214
                                </option><option>VKLE 312
                                </option><option>VPEK 311
                                </option><option>VPEK 874
                                </option><option>VPEK 876
                                </option><option>VPFI 111
                                </option><option>VPFP 171
                                </option><option>VPGI 111
                                </option><option>VPGP 171
                                </option><option>VPGP 271
                                </option><option>VPGR 211
                                </option><option>VPGS 311
                                </option><option>VPGW 211
                                </option><option>VPNN 411
                                </option><option>VPPF 411
                                </option><option>VPVA 412
                                </option><option>VPVN 311
                                </option><option>VPWB 211
                                </option><option>VPWP 271
                                </option><option>VPXP 371
                                </option><option>VPXS 311
                                </option><option>VTEE 212
                                </option><option>VTEE 312
                                </option><option>VTEE 412
                                </option><option>VVBG 211
                                </option><option>VVBG 311
                                </option><option>VVDL 112
                                </option><option>VVDL 213
                                </option><option>VWTL 311
                                </option><option>VWVD 511
                                </option><option>VWVD 512
                                </option><option>WIPN 315
                                </option><option>WISN 111
                                </option><option>WISN 112
                                </option><option>WISN 113
                                </option><option>WISN 211
                                </option><option>WISN 212
                                </option><option>WISN 312
                                </option><option>WISN 313
                                </option><option>WISN 613
                                </option><option>WISO 611
                                </option><option>WISS 111
                                </option><option>WISS 112
                                </option><option>WISS 113
                                </option><option>WSKT 212
                                </option><option>WVCS 315
                                </option><option>WVES 311
                                </option><option>WVET 211
                                </option><option>WVLS 311
                                </option><option>WVLS 312
                                </option><option>WVLS 313
                                </option><option>WVLS 314
                                </option><option>WVNS 211
                                </option><option>WVOS 311
                                </option><option>WVOS 312
                                </option><option>WVTS 211
                                </option><option>XHFF 111
                                </option><option>XHFF 211
                                </option><option>XHFF 311
                                </option><option>XHFF 411
                                </option><option>ZOND 511
                                </option><option>ZUCN 315
                                </option><option>ZUFF 111
                                </option><option>ZUFF 211
                                </option><option>ZUFF 311
                                </option><option>ZUFF 411
                                </option><option>ZUFI 111
                                </option>

                            </select>
                        </div>                
                
                <!-- Faculty input-->
                        <div class="form-group">
                            <label for="selFaculty">Faculty</label>
                            <select class="form-control " name="selFaculty" placeholder = "Select Faculty">
                                    <option>Humanities</option>
                                    <option>Health Sciences</option>
                                    <option>Education</option>
                                    <option>Theology</option>
                                    <option>Law</option>
                                    <option>Engineering</option>
                                    <option>Economic and Management Sciences</option>
                                    <option>Natural and Agricultural Sciences</option>
                            </select>
                        </div>

               <!-- Academic year of Study -->
                        <div class="form-group sb">
                            <label for="selYOS">Academic year of study</label>
                            <select class="form-control" name="selYOS" >
                                <option>1st Year</option>
                                <option>2nd Year</option>
                                <option>3rd Year</option>
                                <option>4th Year</option>
                                <option>Post Grad</option>
                            </select>
                        </div>

                <!-- Textbook Price -->
                        <div class="form-group">
                            <label for="\Book_Price">Textbook Price</label>
                            <input type="text" class="form-control" name="Book_Price" placeholder="Enter Price (ZAR)" required>
                        </div>

		<div class="input-group">
			<button type="submit" class="btn btn-success btn-block" name="Add_item">Add item for sale</button>
		</div>
       
        </div>
        </form> <!-- End of form container -->
        
        
        <!-- Footer -->
        <div class="col-md4 col-sm-8 col-xs-8">
            <div class="footer">
                <footer> ©2018 TextBids - An online 2nd hand texbook trading platform.Created by the students for the students </footer>
            </div>
        </div> 
        
    </div> <!-- End of background class -->

</body>
</html>